Put ZSS in an independent launch group (backward-compatible)
zowe/zowe-install-packaging pull request #1632
Opened 2020-09-03 00:00 UTC by 1000TurquoisePogs

Please check if your PR fulfills the following requirements. This is simply a reminder of what we are going to look for before merging your PR. If you don't know all of this information when you create this PR, don't worry. You can edit this template as you're working on it.

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Necessary documentation (if appropriate) have been added / updated
- [x] DCO signoffs have been added to all commits, including this PR

#### PR type
What type of changes does your PR introduce to Zowe? _Put an `x` in the box that applies to this PR. If you're unsure about any of them, don't hesitate to ask._ 

- [x] Feature 

#### Changes proposed in this PR
The relationship between ZSS and app-server were not fully exposed previously. In order to use ZSS, you had to also have app-server running. But, this is not really how it works. I'm moving ZSS into its own component group so that it can be started independently, but only if people specify that. If they dont, and just continue to specify DESKTOP, then zss should still load as a prereq to app-server. Additionally, zss is not present on Docker, so I do not put it into the list if this script is not running on z/os.

#### Does this PR introduce a breaking change?

- [x] No

The documentation should be amended to explain this option to have ZSS without app-server, although I don't think it will be necessary for most all-zos installs, it will be useful for docker users.

2020-09-04 08:45 UTC, stevenhorsman requested changes
Also need test runs linked

2020-09-08 19:37 UTC, jackjia-ibm reviewed
I'm not 100% sure. Will this have any compatibility issue if user upgrade from FMID? In that case, the user won't have ZSS in LAUNCH_COMPONENT_GROUPS defined.

2020-09-08 22:39 UTC, Joe-Winchester commented
> I'm not 100% sure. Will this have any compatibility issue if user upgrade from FMID? In that case, the user won't have ZSS in LAUNCH_COMPONENT_GROUPS defined.

The component groups are in each instance.env file, so the absence of ZSS should be OK because a user that has DESKTOP will get ZSS launched following Sean's logic.  If a user adds ZSS and DESKTOP this is belt and braces.  The instance.env is in the instance directory which is not affected by an SMP/E (or convenience) upgrade.  We could add ZSS as a new default so that when zowe-configure-instance.sh is run the three values are DESKTOP, ZSS, GATEWAY which would let folks know they can just have ZSS by itself which might be a nice touch, however ZSS only is going to just be for the docker container scenario in which case a lot of the other instance.env variables are not required (Java, Node, lots of ports) so maybe there should be a `zowe-configure-instance.sh` arg that creates a stripped down instance.env and directory that is just optimized for supporting containers only, and also has some steps to help with AT-TLS.

2020-09-11 19:45 UTC, 1000TurquoisePogs commented on bin/internal/run-zowe.sh
> +  if [ `uname` = "OS/390" ]; then
i will see if i can do that in a way that is cross-platform

2020-09-11 19:48 UTC, 1000TurquoisePogs commented
>so maybe there should be a zowe-configure-instance.sh arg that creates a stripped down instance.env and directory that is just optimized for supporting containers only, and also has some steps to help with AT-TLS.
Very possibly Joe. I'm reviewing all the documentation and it's a huge task to compartmentalize it so that the users are not surprised when they dont see missing variables.
I think what would be good is in the case that docker is intended, the instance.env has all the unneeded variables as commented out with a description about why. Then, they can uncomment them if they want to.

2020-09-11 19:48 UTC, 1000TurquoisePogs commented
I will work on Steve's test & refactoring comment.

2020-10-08 19:23 UTC, closed without merging