Move the gw configuration from the start.sh to the instance.env
zowe/zowe-install-packaging pull request #1741
Opened 2020-10-14 14:32 UTC by taban03

Signed-off-by: at670475 <andrea.tabone@broadcom.com>

Please check if your PR fulfills the following requirements. This is simply a reminder of what we are going to look for before merging your PR. If you don't know all of this information when you create this PR, don't worry. You can edit this template as you're working on it.

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Necessary documentation (if appropriate) have been added / updated
- [ ] DCO signoffs have been added to all commits, including this PR

#### PR type
What type of changes does your PR introduce to Zowe? _Put an `x` in the box that applies to this PR. If you're unsure about any of them, don't hesitate to ask._ 
- [ ] Bugfix 
- [ ] Feature 
- [ ] Other... Please describe:

#### Relevant issues

Fixes 

#### Changes proposed in this PR

- 

#### Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

#### Does this PR do something the person installing Zowe should know about?

---
* Affected function: _general area of interest_ *

---
* Description: _1 line description_ *

---
* Part: _name of customizable file involved_  *

---
_multi-line description_

#### Is there a related doc issue or Pull Request? 

Doc issue/PR number: 

#### Other information

2020-10-16 15:51 UTC, stevenhorsman requested changes

2020-10-16 15:51 UTC, stevenhorsman commented on playbooks/roles/configfmid/defaults/main.yml
> +zowe_apiml_security_zosmf_applid: IZUDFLT
we don't want the new properties in the fmid as that is based on 1.9

2020-10-16 15:51 UTC, stevenhorsman commented on playbooks/roles/configfmid/tasks/configure_instance.yml
> +    sed -e "s+^APIML_SECURITY_ZOSMF_APPLID=.*\$+APIML_SECURITY_ZOSMF_APPLID={{ zowe_apiml_security_zosmf_applid|string|lower }}+" | \
again, not needed on the configurefmid

2020-10-16 15:51 UTC, stevenhorsman commented on playbooks/roles/configfmid/tasks/main.yml
> +    - zowe_apiml_security_zosmf_applid
Same comment

2020-10-19 06:52 UTC, taban03 commented on playbooks/roles/configfmid/tasks/configure_instance.yml
> +    sed -e "s+^APIML_SECURITY_ZOSMF_APPLID=.*\$+APIML_SECURITY_ZOSMF_APPLID={{ zowe_apiml_security_zosmf_applid|string|lower }}+" | \
Thank you Steven, I'm gonna fix it

2020-10-19 12:16 UTC, stevenhorsman commented
convenience tests: https://wash.zowe.org:8443/job/zowe-install-test/view/change-requests/job/PR-1741/9/
ptf tests: https://wash.zowe.org:8443/job/zowe-install-test/view/change-requests/job/PR-1741/10/

2020-10-19 12:16 UTC, stevenhorsman approved these changes

2020-10-19 12:16 UTC, merged