[WIP] create vsam data set
zowe/zowe-install-packaging pull request #1760
Opened 2020-10-28 17:06 UTC by jackjia-ibm

Please check if your PR fulfills the following requirements. This is simply a reminder of what we are going to look for before merging your PR. If you don't know all of this information when you create this PR, don't worry. You can edit this template as you're working on it.

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Necessary documentation (if appropriate) have been added / updated
- [x] DCO signoffs have been added to all commits, including this PR

#### PR type
What type of changes does your PR introduce to Zowe? _Put an `x` in the box that applies to this PR. If you're unsure about any of them, don't hesitate to ask._ 
- [ ] Bugfix 
- [x] Feature 
- [ ] Other... Please describe:

#### Relevant issues

Fixes https://github.com/zowe/zowe-install-packaging/issues/1688 as research result of https://github.com/zowe/api-layer/issues/889.

#### Changes proposed in this PR

- Place sample JCLs to create VSAM data set into SAMPLIB
- Add new playbook task to create VSAM data set

#### Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

#### Does this PR do something the person installing Zowe should know about?

---
* Affected function:  Configure Zowe instance *

---
* Description: Provide samples to create VSAM data set for Zowe Caching Service *

---
* Part: SZWESAMP(ZWECSVMP), SZWESAMP(ZWECSVPX)  *

---
When preparing a Zowe instance in High Availability theme, it's required to create
VSAM data set which is used to persist state data for Zowe caching server.
If you are running Zowe in Parallel Sysplex, SZWESAMP(ZWECSVPX)  should be
used. If you are running Zowe in Monoplex, SZWESAMP(ZWECSVMP) should be
customized and executed. Please read instructions on top of the sample JCL
before submitting it.

#### Is there a related doc issue or Pull Request? 

Doc issue/PR number: 

#### Other information

2020-10-30 14:55 UTC, jackjia-ibm commented
Tests done:
Convenience build: https://wash.zowe.org:8443/view/Zowe/job/zowe-install-test/view/change-requests/job/PR-1760/6/
SMPE: https://wash.zowe.org:8443/view/Zowe/job/zowe-install-test/view/change-requests/job/PR-1760/7/

2020-11-02 10:42 UTC, stevenhorsman approved these changes
Looks plausible to me

2020-11-03 01:59 UTC, OnnoVdT requested changes

2020-11-03 01:59 UTC, OnnoVdT commented on scripts/instance.template.env
> +# specify the same data set name created by ZWECSVSM jcl
`# specify the data set name of the caching service VSAM`
you don't specify names of other setup jobs as reference, so don't do it here either

2020-11-03 01:59 UTC, OnnoVdT commented on files/jcl/ZWECSVSM.jcl
> +//ZWECSVSM JOB
Your IDCAMS comments will cause JCL and IDCAMS errors. Also, deleting semi-random lines based on whether you want RLS or not is asking for errors, so it's better to provide two blocks, and a simple switch between them.
I reworked the JCL and attached it here.

[ZWECSVSM.jcl.txt](https://github.com/zowe/zowe-install-packaging/files/5478894/ZWECSVSM.jcl.txt)

2020-11-03 14:07 UTC, OnnoVdT approved these changes

2020-11-04 13:40 UTC, jackjia-ibm commented
Build has been verified with https://wash.zowe.org:8443/view/Zowe/job/zowe-install-test/view/change-requests/job/PR-1760/9/ and https://wash.zowe.org:8443/view/Zowe/job/zowe-install-test/view/change-requests/job/PR-1760/10/

2020-11-04 13:41 UTC, merged