Scripts for zowe launcher
zowe/zowe-install-packaging pull request #1970
Opened 2021-02-20 04:31 UTC by lchudinov

### Scripts for Zowe Launcher
#### PR type
- [x] Feature 

#### Relevant issues
https://app.zenhub.com/workspaces/community-5c93e02fa70b456d35b8f0ed/issues/zowe/zlux/590

#### Changes proposed in this PR
- PR adds scripts for Zowe Launcher

#### Does this PR introduce a breaking change?

- [x] No

2021-02-22 14:17 UTC, 1000TurquoisePogs requested changes
Zowe launcher path needs to be changed somehow.
https://github.com/zowe/launcher/pull/18 mentions /bin/zowe_launcher
That could be OK, but lets hear from Jack.

2021-02-22 14:17 UTC, 1000TurquoisePogs commented on bin/internal/run-zowe.sh
> +  ${ROOT_DIR}/components/launcher/bin/zowe_launcher "${launch_components_list}"
The launcher isn't a component but it starts components. There should be a different location for zowe launcher. Perhaps ${ROOT_DIR}/bin/launcher or similar.

2021-02-23 02:52 UTC, jackjia-ibm commented
I agree `${ROOT_DIR}/bin/launcher` is a better location. Launcher is packaged with manifest, but it's not a regular component. It makes sense to put into `${ROOT_DIR}/bin` folder to avoid confusion.

2021-03-30 04:07 UTC, jackjia-ibm commented
Hi @lchudinov, I'm thinking to merge this PR with YAML config related changes in https://github.com/zowe/zowe-install-packaging/pull/2049. To make it compatible, I made a small change on the shell script name here https://github.com/zowe/launcher/pull/18/commits/73541a9de4c6bb2fa7d2c5d72399dbf74f642f37#diff-e0cf5b28d9b6b600f0af2bc78e8fd30ec675fd731a5da86f0c4283ffc0e40176L852-R879.

I will do an integration test first and make changes related to process IDs handling. Later I will need your help to make a change to add HA_INSTANCE_ID as procedure parameter. It will be a pass through parameter. Thanks a lot Leonty!

2021-04-15 18:49 UTC, jackjia-ibm commented
Close because similar features had been merged into #2049 and merged into staging branch.

2021-04-15 18:49 UTC, closed without merging