Fix nightly staging docker
zowe/zowe-install-packaging pull request #2293
Opened 2021-08-13 14:25 UTC by FlappiTomic

Signed-off-by: Tom Zhang <14881754+FlappiTomic@users.noreply.github.com>

Please check if your PR fulfills the following requirements. This is simply a reminder of what we are going to look for before merging your PR. If you don't know all of this information when you create this PR, don't worry. You can edit this template as you're working on it.

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Necessary documentation (if appropriate) have been added / updated
- [ ] DCO signoffs have been added to all commits, including this PR

#### PR type
What type of changes does your PR introduce to Zowe? _Put an `x` in the box that applies to this PR. If you're unsure about any of them, don't hesitate to ask._ 
- [ ] Bugfix 
- [ ] Feature 
- [ ] Other... Please describe:

#### Relevant issues

Fixes 

#### Changes proposed in this PR

- 

#### Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

#### Does this PR do something the person installing Zowe should know about?

---
* Affected function: _general area of interest_ *

---
* Description: _1 line description_ *

---
* Part: _name of customizable file involved_  *

---
_multi-line description_

#### Is there a related doc issue or Pull Request? 

Doc issue/PR number: 

#### Other information

2021-08-13 21:51 UTC, FlappiTomic commented
@jackjia-ibm I think this is the fix for this issue...

2021-08-16 13:13 UTC, jackjia-ibm requested changes
Let's leave this PR open for a while and see if we can find more on the root cause. It doesn't make sense why SSH `localhost` works for conv build test but failed for docker test.

2021-08-16 13:13 UTC, jackjia-ibm commented on playbooks/roles/docker/tasks/docker-start.yml
> +      --env ZOWE_ZLUX_SSH_HOST=zzow01.zowe.marist.cloud \
Should use `zowe_zos_host` variable.

2021-08-16 15:00 UTC, 1000TurquoisePogs commented
I'm confused how this happened, since the code for `ZOWE_ZLUX_SSH_HOST` hasn't changed in the year 2021.

2021-08-19 20:08 UTC, FlappiTomic commented on playbooks/roles/docker/tasks/docker-start.yml
> +      --env ZOWE_ZLUX_SSH_HOST=zzow01.zowe.marist.cloud \
Changed

2021-08-31 18:44 UTC, merged