User/pavelzlatnik/fix zweconf yaml generator
zowe/zowe-install-packaging pull request #3761
Opened 2024-03-14 10:27 UTC by muzikovam

Please check if your PR fulfills the following requirements. This is simply a reminder of what we are going to look for before merging your PR. If you don't know all of this information when you create this PR, don't worry. You can edit this template as you're working on it.

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Necessary documentation (if appropriate) have been added / updated
- [x] DCO signoffs have been added to all commits, including this PR

#### PR type
What type of changes does your PR introduce to Zowe? _Put an `x` in the box that applies to this PR. If you're unsure about any of them, don't hesitate to ask._ 
- [x] Bugfix 
- [ ] Feature 
- [ ] Other... Please describe:

#### Relevant issues

Fixes 
#3411
#### Changes proposed in this PR

- Fixes in configuration workflow - creating zowe.yaml file correctly, some variables shouldn't be required.

#### Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

#### Does this PR do something the person installing Zowe should know about?

---
* Affected function: ZWECONF.xml *

---
* Description: Fixes creation of zowe.yml *

---
* Part: ZWECONF.xml  *

---
_multi-line description_

#### Is there a related doc issue or Pull Request? 

Doc issue/PR number: 

#### Other information

2024-03-15 09:59 UTC, donkeykin requested changes
<title>Change ownership</title>
        <description>This step changes the ownership and mode of the ZOWE USS directory so the zwe command can be called.</description>
        <instructions substitution="false">Make sure you have the correct SYSAFF in the following JCL so the filesystem is
         mounted correctly.
        </instructions>

2024-03-15 14:52 UTC, MarkAckert approved these changes

2024-03-18 09:04 UTC, donkeykin commented on workflows/files/ZWEWRF02.xml
> +        <description>This step changes the ownership and mode of ZOWE USS directory so the zwe command can be called.</description>
This step changes the ownership and mode of the ZOWE USS directory so the zwe command can be called.

2024-03-18 09:04 UTC, donkeykin commented on workflows/files/ZWEWRF02.xml
> +        <instructions substitution="false">Make sure you have correct SYSAFF in the following JCL so the filesystem is
Make sure you have the correct SYSAFF in the following JCL so the filesystem is
         mounted correctly.

2024-03-18 09:06 UTC, donkeykin commented on workflows/files/ZWECONF.properties
> +# Abstract: Load library where Zowe will store libraries Utilities for use by Zowe and extensions
Load library where Zowe stores libraries for Utilities for use by Zowe and extensions

2024-03-18 09:08 UTC, donkeykin commented on workflows/files/ZWECONF.properties
> +# Abstract: Set to "exit" or "warn" what to do, if any component has an error
Set to "exit" or "warn" if any component has an error

2024-03-18 09:09 UTC, donkeykin commented on workflows/files/ZWECONF.properties
> +#  Set to "exit" if you'd like startup to exit if any component has an error in the configure stage, otherwise zwe will warn but continue.
Set to "exit" if you want startup to exit if any component has an error in the configuration stage, otherwise zwe will issue a warning but continue running.

2024-03-18 09:14 UTC, donkeykin commented on workflows/files/ZWECONF.properties
> +#  Whether the agent will issue and accept cookies from itself in the event a JWT cannot be provided
This is unclear .. If fallback is enabled, does the agent issue and accept cookies from itself in the event a JWT cannot be provided?

2024-03-18 09:24 UTC, donkeykin commented on workflows/files/ZWECONF.properties
> +# Abstract: ID that can be used by servers that distinguish their cookies from unrelated Zowe installs
ID that can be used by servers to distinguish their cookies from unrelated Zowe installs

2024-03-18 09:24 UTC, donkeykin commented on workflows/files/ZWECONF.properties
> +#  ID when determining for purposes such as to allow multiple copies of Zowe to be used within the same client
ID which allows multiple copies of Zowe to be used within the same client

2024-03-18 10:01 UTC, janan07 reviewed
I approve Lawrence's comments.

2024-03-18 15:18 UTC, merged