V3: update example-zowe.yaml for ZWEAM001I
zowe/zowe-install-packaging pull request #4025
Opened 2024-09-30 17:43 UTC by 1000TurquoisePogs

- [x] Necessary documentation (if appropriate) have been added / updated
- [x] DCO signoffs have been added to all commits, including this PR

#### Relevant issues
Implements https://github.com/zowe/docs-site/pull/3894

This PR just changes the example config to add the new message ZWEAM001I to syslog

2024-10-01 07:26 UTC, balhar-jakub approved these changes
Thanks for preparing

2025-10-03 08:52 UTC, Martin-Zeithaml requested changes, later dismissed
This will fail (when merging -> not unique item) if user defines any subset from defaults.
We can only update `example-zowe.yaml`.

2026-02-25 10:47 UTC, Martin-Zeithaml approved these changes
Ideally this should be approved again by someone from Zowe Community.

2026-02-27 14:47 UTC, MarkAckert commented
This PR needs to address the `PSWI zowe.yaml sync` automation before it can be merged in. The regular-build should be passing too, but I think the current failure is unrelated to the changes here.

2026-03-02 15:40 UTC, MarkAckert approved these changes

2026-04-01 14:34 UTC, merged